spring:
  application:
    name: shishaBuddiesDB
  datasource:
    url: jdbc:postgresql://localhost:5432/shishaBuddiesDB
    username: admin
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true

